version: "3"
services:
  psui-server:
     image: psui-server
     networks:
       - psui
     ports:
       - 3000:3000
     environment:
       NODE_ENV: production
  psui-app:
     image: psui-app
     networks:
       - psui
     ports:
       - 4200:4200
     environment:
       NODE_ENV: production
     volumes:
       app_dist:/app/dist/
  psui-nginx:
    image: psui-nginx
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
    networks:
      - psui
    volumes:
      app_dist:/data/
    deploy:
      replicas: 3
networks:
  psui:
volumes:
  app_dist:
