version: "3"
services:
  psui-server:
     image: psui-server
     networks:
       - psui
     ports:
       - 3000:3000
     environment:
       NODE_ENV: production
  psui-app:
     image: psui-app
     networks:
       - psui
     ports:
       - 4200:4200
     environment:
       NODE_ENV: production
networks:
  psui:
