version: "3"
services:
  server:
     build:
       context: ../../
       dockerfile: enviroments/development/server.dockerfile
     command: meteor -p server:3000
     volumes:
       - ../../api/server:/api/server
     networks:
       - psui
     ports:
       - 3000:3000
     environment:
       NODE_ENV: development
  app:
     build:
       context: ../../
       dockerfile: enviroments/development/app.dockerfile
     command: npm run start
     volumes:
       - ../../src:/app/src/:rw
     networks:
       - psui
     ports:
       - 4200:4200
     environment:
       NODE_ENV: development
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodbdata:/data/db
    networks:
      - psui
volumes:
  mongodbdata:
networks:
  psui:
