version: "3.2"
services:
  server:
     image: server_prod
     command: node dist/bundle/main.js
     networks:
       - frontend
     ports:
       - 3000:3000
     environment:
       NODE_ENV: production
  app:
     image: app_prod
     networks:
       - frontend
     environment:
       NODE_ENV: production
     ports:
       - target: 80
         published: 80
         protocol: tcp
         mode: host
networks:
  frontend:
    external: true
